files:
  upload-dir: /upload
server:
  port: ${PORT:9456}
  servlet:
    context-path: /resource-server-jwt
spring:
  security:
    oauth2:
      resourceserver:
         jwt:
           jws-algorithms: RS512
           issuer-uri: https://idp.example.com/issuer
  datasource:
    url: ${DB_URL:jdbc:h2:file:./tmp/manager_crm}
    username: ${DB_USERNAME:joaovq}
    password: ${DB_PASSWORD:}
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  sql:
    init:
      mode: always
springdoc:
  api-docs:
        path: /api-docs
cors:
  origins: ${CORS_ORIGINS:http://localhost:3000,http://localhost:8080}