server:
  port: 9456
spring:
  datasource:
    url: ${DB_URL:jdbc:h2:file:./data/manager_crm}
    username: ${DB_USERNAME:joaovq}
    password: ${DB_PASSWORD:}
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  sql:
    init:
      mode: always